export const CHECK_TREASURE = 'CHECK_TREASURE';
export const TREASURE_DATA_EXISTS = 'TREASURE_DATA_EXISTS';
export const FETCH_TREASURE_SUCCESS = 'FETCH_TREASURE_SUCCESS';
export const FETCH_TREASURE_ERROR = 'FETCH_TREASURE_ERROR';
